"""
Meeting Summarizer Engine.
Supports Cloud LLMs (Groq, OpenAI, Gemini) and Local LLMs (Ollama)
to generate structured executive meeting notes, action items, and decisions.
"""

from __future__ import annotations

import json
import logging
from typing import Optional

import aiohttp

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are DisWhisper AI, an expert executive meeting assistant.
Given a raw meeting transcript with participant names and timestamps, produce a clear, structured summary in Markdown format:

### 📌 Executive Summary
Provide a concise 2-3 paragraph overview of the meeting and main themes.

### 🎯 Key Discussion Topics
Bullet points detailing key discussion topics and points of consensus.

### ✅ Action Items & Tasks
List concrete action items, specifying who is responsible (if mentioned) and what the next step is. Format:
- [ ] **[Person Name]:** Task description.

### 💡 Key Decisions & Conclusions
Bullet points detailing decisions agreed upon during the conversation.

Be professional, concise, and preserve the original tone and context without hallucinating information."""


class MeetingSummarizer:
    """
    Generates structured meeting summaries from transcripts using Cloud or Local LLMs.
    """

    def __init__(
        self,
        provider: str = "cloud",
        cloud_platform: str = "groq",
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
        local_llm_url: str = "http://localhost:11434",
    ):
        self.provider = provider.lower().strip()
        self.cloud_platform = cloud_platform.lower().strip()
        self.api_key = api_key or ""
        self.model_name = model_name or (
            "llama-3.3-70b-versatile" if self.cloud_platform == "groq" else "gpt-4o-mini"
        )
        self.local_llm_url = local_llm_url.rstrip("/")

    async def summarize_transcript(self, transcript_text: str) -> str:
        """
        Generate structured summary for the provided transcript string.
        """
        if not transcript_text or not transcript_text.strip():
            return "⚠️ Cannot summarize an empty transcript."

        if self.provider == "local":
            return await self._summarize_local(transcript_text)
        else:
            return await self._summarize_cloud(transcript_text)

    async def _summarize_cloud(self, transcript_text: str) -> str:
        """Call Groq, OpenAI, or compatible cloud LLM endpoint."""
        if not self.api_key:
            return f"❌ Missing API key for {self.cloud_platform.upper()} LLM summarizer."

        if self.cloud_platform == "groq":
            url = "https://api.groq.com/openai/v1/chat/completions"
        elif self.cloud_platform == "openai":
            url = "https://api.openai.com/v1/chat/completions"
        else:
            url = "https://api.groq.com/openai/v1/chat/completions"

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": self.model_name,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Meeting Transcript:\n\n{transcript_text}"},
            ],
            "temperature": 0.2,
        }

        try:
            timeout = aiohttp.ClientTimeout(total=45.0)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(url, headers=headers, json=payload) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        choices = data.get("choices", [])
                        if choices:
                            return choices[0]["message"]["content"].strip()
                        return "⚠️ No summary generated by LLM."
                    else:
                        err_text = await resp.text()
                        logger.error(f"Cloud LLM API error ({resp.status}): {err_text}")
                        return f"❌ Cloud LLM Error: HTTP {resp.status} - {err_text[:200]}"
        except Exception as e:
            logger.error(f"Exception during cloud summarization: {e}", exc_info=True)
            return f"❌ Error contacting cloud LLM: {e}"

    async def _summarize_local(self, transcript_text: str) -> str:
        """Call local Ollama instance (http://localhost:11434)."""
        url = f"{self.local_llm_url}/api/chat"

        payload = {
            "model": self.model_name or "llama3.2",
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Meeting Transcript:\n\n{transcript_text}"},
            ],
            "stream": False,
        }

        try:
            timeout = aiohttp.ClientTimeout(total=90.0)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(url, json=payload) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        msg = data.get("message", {}).get("content", "")
                        return msg.strip()
                    else:
                        err_text = await resp.text()
                        logger.error(f"Local Ollama error ({resp.status}): {err_text}")
                        return f"❌ Local Ollama Error: HTTP {resp.status}. Ensure Ollama is running at {self.local_llm_url}."
        except aiohttp.ClientConnectorError:
            return f"❌ Could not connect to local Ollama at {self.local_llm_url}. Please ensure Ollama is installed and running (`ollama serve`)."
        except Exception as e:
            logger.error(f"Exception during local summarization: {e}", exc_info=True)
            return f"❌ Local LLM error: {e}"
